/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1/userguide/multi_project_builds.html
 */

rootProject.name = "s2122v-li42d"
include("aula-03-17-22")
include("aula-03-24")
include("aula-03-29")
include("aula-04-05")
include("aula-04-07")
