/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1/userguide/multi_project_builds.html
 */

rootProject.name = "s2122v-li42d"
include("aula-03-17-22")
include("aula-03-24")
include("aula-03-29")
include("aula-04-05")
include("aula-04-07")
include("aula-04-12")
include("aula-04-19")
include("aula-04-21-part1")
include("aula-04-21-part2")
include("aula-04-26")
include("aula-04-28")
include("aula-05-05-async-intro")
include("aula-05-10-completable-futures-intro")
include("aula-05-12-echo-server-with-CF")
include("aula-05-17-echo-server-cf-with-shutdown")
include("aula-05-19-coroutines-intro")
include("aula-05-24")
include("aula-05-26")
include("aula-05-31-asynchronizers")
include("aula-06-02")
